version: "3.9"

services:
  api:
    container_name: bit_api
    build: ./src
    ports:
      - "5000:5000"
    environment:
      MONGO_HOST: 'mongodb://db'
      MONGO_PORT: 27017
    depends_on:
      - db

  db:
    container_name: bit_mongo
    image: mongo:latest
    volumes:
      - mongo:/data/db

volumes:
  mongo:
