version: "3.9"

services:
  api:
    container_name: bit_api
    build: ./src
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment:
      MONGO_CONNECTION: 'mongodb://db:27017'
    depends_on:
      - db

  db:
    container_name: bit_mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

volumes:
  mongo:
